FROM --platform=linux/amd64 python:3.11.9-slim as build

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG SERVER_SECRET_KEY
ARG KAKAO_CLIENT_ID
ARG KAKAO_RESTAPI_KEY
ARG NAVER_CLIENT_ID
ARG NAVER_SECRET_KEY
ARG DATABASE_HOST
ARG DATABASE_USER
ARG DATABASE_PWD
ARG DATABASE_NAME
ARG BUSINESS_SERVICE_KEY
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG REGION_NAME
ARG BUCKET_NAME
ARG SGISAPI_KEY
ARG SGISAPI_SECRET

ENV SERVER_SECRET_KEY=${SERVER_SECRET_KEY}
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
ENV KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ENV NAVER_SECRET_KEY=${NAVER_SECRET_KEY}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PWD=${DATABASE_PWD}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV BUSINESS_SERVICE_KEY=${BUSINESS_SERVICE_KEY}
ENV AWS_ACCESS_KEY_ID_=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY_=${AWS_SECRET_ACCESS_KEY}
ENV REGION_NAME=${REGION_NAME}
ENV BUCKET_NAME=${BUCKET_NAME}
ENV SGISAPI_KEY=${SGISAPI_KEY}
ENV SGISAPI_SECRET=${SGISAPI_SECRET}

WORKDIR /code

# Copy requirements and application code
COPY ./requirements.txt /code/requirements.txt
COPY ./app /code/app

# Create .env file with the environment variables
RUN echo "\
    SERVER_SECRET_KEY=${SERVER_SECRET_KEY}\n\
    KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}\n\
    KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}\n\
    NAVER_CLIENT_ID=${NAVER_CLIENT_ID}\n\
    NAVER_SECRET_KEY=${NAVER_SECRET_KEY}\n\
    DATABASE_HOST=${DATABASE_HOST}\n\
    DATABASE_USER=${DATABASE_USER}\n\
    DATABASE_PWD=${DATABASE_PWD}\n\
    DATABASE_NAME=${DATABASE_NAME}\n\
    BUSINESS_SERVICE_KEY=${BUSINESS_SERVICE_KEY}\n\
    AWS_ACCESS_KEY_ID_=${AWS_ACCESS_KEY_ID}\n\
    AWS_SECRET_ACCESS_KEY_=${AWS_SECRET_ACCESS_KEY}\n\
    REGION_NAME=${REGION_NAME}\n\
    BUCKET_NAME=${BUCKET_NAME}\n\
    SGISAPI_KEY=${SGISAPI_KEY}\n\
    SGISAPI_SECRET=${SGISAPI_SECRET}\n\
    " > /usr/src/app/.env

# Install dependencies
RUN pip install --no-cache-dir -r /code/requirements.txt

WORKDIR /usr/src/app
COPY ./app /usr/src/app

EXPOSE 80
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
