name: Deploy with Docker

on:
  push:
    branches: 
      - ec2 

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/lets_server_image
  VERSION: ${{ github.sha }}
  NAME: lets_server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Create .env file
      run: |
        echo "SERVER_SECRET_KEY=${{ secrets.SERVER_SECRET_KEY }}" >> .env
        echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
        echo "KAKAO_RESTAPI_KEY=${{ secrets.KAKAO_RESTAPI_KEY }}" >> .env
        echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
        echo "NAVER_SECRET_KEY=${{ secrets.NAVER_SECRET_KEY }}" >> .env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
        echo "DATABASE_PWD=${{ secrets.DATABASE_PWD }}" >> .env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
        echo "BUSSINESS_SERVICE_KEY=${{ secrets.BUSSINESS_SERVICE_KEY }}" >> .env
        echo "AWS_ACCESS_KEY_ID_=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY_=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "REGION_NAME=${{ secrets.REGION_NAME }}" >> .env
        echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
        echo "SGISAPI_KEY=${{ secrets.SGISAPI_KEY }}" >> .env
        echo "SGISAPI_SECRET=${{ secrets.SGISAPI_SECRET }}" >> .env    

      
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-lets ]

    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} || true
          docker rm ${{ env.NAME }} || true
          docker rmi ${{ env.DOCKER_IMAGE }}:latest || true
          docker run -dit -p 80:80 --name ${{ env.NAME }} \
          --restart always ${{ env.DOCKER_IMAGE }}:latest
